files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 82184E6E6BF21D7C0E91DE0BD7609E90
  logicalPath: config/pic32mz_ef_btadk_ak4954/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 82184E6E6BF21D7C0E91DE0BD7609E90
- generatedChecksum: 774AAF4E54A4DB1EB558009DB900EB46
  logicalPath: config/pic32mz_ef_btadk_ak4954/audio/driver/codec/ak4954
  name: drv_ak4954.c
  physicalPath: audio/driver/codec/ak4954
  security: NON_SECURE
  type: SOURCE
  userChecksum: 774AAF4E54A4DB1EB558009DB900EB46
- generatedChecksum: D7CB7F305208715624357B71229B20B4
  logicalPath: config/pic32mz_ef_btadk_ak4954/audio/driver/codec/ak4954
  name: drv_ak4954_local.h
  physicalPath: audio/driver/codec/ak4954
  security: NON_SECURE
  type: SOURCE
  userChecksum: D7CB7F305208715624357B71229B20B4
- generatedChecksum: 39534E1CE0B7BEBCA64DAF598E5024E7
  logicalPath: config/pic32mz_ef_btadk_ak4954/driver/i2c
  name: drv_i2c.c
  physicalPath: driver/i2c/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 39534E1CE0B7BEBCA64DAF598E5024E7
- generatedChecksum: 37780F17759DED907A0F36E28BFB3136
  logicalPath: config/pic32mz_ef_btadk_ak4954/driver/i2c
  name: drv_i2c_local.h
  physicalPath: driver/i2c/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 37780F17759DED907A0F36E28BFB3136
- generatedChecksum: AF0B16E0482BD623C201B23916653971
  logicalPath: config/pic32mz_ef_btadk_ak4954/audio/driver/i2s
  name: drv_i2s.c
  physicalPath: audio/driver/i2s/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: AF0B16E0482BD623C201B23916653971
- generatedChecksum: B4725BD9958F563F4B5B26712B1E69CE
  logicalPath: config/pic32mz_ef_btadk_ak4954/audio/driver/i2s
  name: drv_i2s_local.h
  physicalPath: audio/driver/i2s/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: B4725BD9958F563F4B5B26712B1E69CE
- generatedChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D230A6B646D2E78CEAA6AA924E04FCA0
- generatedChecksum: 05F5F37EEEEBBD558128810A2EC70215
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 05F5F37EEEEBBD558128810A2EC70215
- generatedChecksum: BCFA2816D7034F280411F6C54359A80A
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: BCFA2816D7034F280411F6C54359A80A
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 3D8C48F74FB68CAD1864F3122F837CE1
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3D8C48F74FB68CAD1864F3122F837CE1
- generatedChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
- generatedChecksum: 706CF9D9EFA2BCAE46AA1E83688FE018
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/dmac
  name: plib_dmac.c
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: SOURCE
  userChecksum: 706CF9D9EFA2BCAE46AA1E83688FE018
- generatedChecksum: 22E09ABB178BB95377CE29D1ACDDFE89
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 22E09ABB178BB95377CE29D1ACDDFE89
- generatedChecksum: 2363B65659BE6AD9693CA5C988F97DB8
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2363B65659BE6AD9693CA5C988F97DB8
- generatedChecksum: 9FA8E6F7097DF374E74B96F1039F51A4
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/i2c/master
  name: plib_i2c1_master.c
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9FA8E6F7097DF374E74B96F1039F51A4
- generatedChecksum: 5C783F7B46CBD7A46A0FC5405DC24C40
  logicalPath: config/pic32mz_ef_btadk_ak4954/audio/peripheral/i2s
  name: plib_i2s2.c
  physicalPath: audio/peripheral/i2s
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5C783F7B46CBD7A46A0FC5405DC24C40
- generatedChecksum: 3AFB6233BB761B549A3BD85467C9F541
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3AFB6233BB761B549A3BD85467C9F541
- generatedChecksum: 2E02308556447B0510575953A9E9DF6E
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/dma
  name: sys_dma.c
  physicalPath: system/dma
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2E02308556447B0510575953A9E9DF6E
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 83BDE663A1AAB20C9E52263F22E2ED3C
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/time
  name: sys_time.c
  physicalPath: system/time/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 83BDE663A1AAB20C9E52263F22E2ED3C
- generatedChecksum: 5E0977475FFB5B562712A42CB9139C54
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5E0977475FFB5B562712A42CB9139C54
- generatedChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
  logicalPath: config/pic32mz_ef_btadk_ak4954/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 5FB617BE61782FBB4894E08E1711345F
  logicalPath: config/pic32mz_ef_btadk_ak4954/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 5FB617BE61782FBB4894E08E1711345F
- generatedChecksum: 1699869B38E91F033980412B25A55DC9
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: B1355C4D0168487439AA251233BD2D49
- generatedChecksum: 1530CE9EAEB77E43E264D78E7B3E844D
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 1530CE9EAEB77E43E264D78E7B3E844D
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mz_ef_btadk_ak4954/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mz_ef_btadk_ak4954/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: C9E105A6A746DB1FCBFAC0F99F47897F
  logicalPath: config/pic32mz_ef_btadk_ak4954/audio/driver/codec/ak4954
  name: drv_ak4954.h
  physicalPath: audio/driver/codec/ak4954
  security: NON_SECURE
  type: HEADER
  userChecksum: C9E105A6A746DB1FCBFAC0F99F47897F
- generatedChecksum: 3C6689B8800C6234028EC2FBE82E25CF
  logicalPath: config/pic32mz_ef_btadk_ak4954/driver/i2c
  name: drv_i2c.h
  physicalPath: driver/i2c
  security: NON_SECURE
  type: HEADER
  userChecksum: 3C6689B8800C6234028EC2FBE82E25CF
- generatedChecksum: 5FA3FDC136CCB667D6952682F7664DE1
  logicalPath: config/pic32mz_ef_btadk_ak4954/driver/i2c
  name: drv_i2c_definitions.h
  physicalPath: driver/i2c
  security: NON_SECURE
  type: HEADER
  userChecksum: 5FA3FDC136CCB667D6952682F7664DE1
- generatedChecksum: 286480D625E01930A6754127AA6F0360
  logicalPath: config/pic32mz_ef_btadk_ak4954/audio/driver/i2s
  name: drv_i2s.h
  physicalPath: audio/driver/i2s
  security: NON_SECURE
  type: HEADER
  userChecksum: 286480D625E01930A6754127AA6F0360
- generatedChecksum: AE82E3B652F0386ADFA939DDC3B8F3FA
  logicalPath: config/pic32mz_ef_btadk_ak4954/audio/driver/i2s
  name: drv_i2s_definitions.h
  physicalPath: audio/driver/i2s
  security: NON_SECURE
  type: HEADER
  userChecksum: AE82E3B652F0386ADFA939DDC3B8F3FA
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mz_ef_btadk_ak4954/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mz_ef_btadk_ak4954/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mz_ef_btadk_ak4954/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 21233A0A53C6AC48E24C8A7C17A33D00
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 21233A0A53C6AC48E24C8A7C17A33D00
- generatedChecksum: D4A1E2329C517DB8AB49B9143079554F
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/dmac
  name: plib_dmac.h
  physicalPath: peripheral/dmac
  security: NON_SECURE
  type: HEADER
  userChecksum: D4A1E2329C517DB8AB49B9143079554F
- generatedChecksum: 815CCB981B6CB758464D89480121DC08
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 815CCB981B6CB758464D89480121DC08
- generatedChecksum: 9B99D7577C1B09B730845F13C97A9908
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 9B99D7577C1B09B730845F13C97A9908
- generatedChecksum: D6ECFE797E49453D076C8DF185763EB9
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/i2c/master
  name: plib_i2c1_master.h
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: HEADER
  userChecksum: D6ECFE797E49453D076C8DF185763EB9
- generatedChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/i2c/master
  name: plib_i2c_master_common.h
  physicalPath: peripheral/i2c/master
  security: NON_SECURE
  type: HEADER
  userChecksum: B963C6FE44292A1C4A14C3BA5BE95AEE
- generatedChecksum: BE06AA80269C9CC117532D9FB369F739
  logicalPath: config/pic32mz_ef_btadk_ak4954/audio/peripheral/i2s
  name: plib_i2s2.h
  physicalPath: audio/peripheral/i2s
  security: NON_SECURE
  type: HEADER
  userChecksum: BE06AA80269C9CC117532D9FB369F739
- generatedChecksum: 3A8ABAF878FD8C5863C9774A793D76EC
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 3A8ABAF878FD8C5863C9774A793D76EC
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mz_ef_btadk_ak4954/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 4A7FFAD7ACF8378CEC16FBF2BC2368BE
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/dma
  name: sys_dma.h
  physicalPath: system/dma
  security: NON_SECURE
  type: HEADER
  userChecksum: 4A7FFAD7ACF8378CEC16FBF2BC2368BE
- generatedChecksum: FF2FADFBBFB94FF4B4A57085D719E7C8
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/dma
  name: sys_dma_mapping.h
  physicalPath: system/dma
  security: NON_SECURE
  type: HEADER
  userChecksum: FF2FADFBBFB94FF4B4A57085D719E7C8
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 6348A6C05D5693300B296BD46CCC535D
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/ports
  name: sys_ports.h
  physicalPath: system/ports
  security: NON_SECURE
  type: HEADER
  userChecksum: 6348A6C05D5693300B296BD46CCC535D
- generatedChecksum: BC6E1661BF4CAC21B70F5F56A0D7BBDB
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/ports
  name: sys_ports_mapping.h
  physicalPath: system/ports
  security: NON_SECURE
  type: HEADER
  userChecksum: BC6E1661BF4CAC21B70F5F56A0D7BBDB
- generatedChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/time
  name: sys_time.h
  physicalPath: system/time
  security: NON_SECURE
  type: HEADER
  userChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
- generatedChecksum: 9463F9BBF69C9593FF3B30F8BC587234
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/time
  name: sys_time_definitions.h
  physicalPath: system/time
  security: NON_SECURE
  type: HEADER
  userChecksum: 9463F9BBF69C9593FF3B30F8BC587234
- generatedChecksum: 62F39464265EC34979649F761FB4FE57
  logicalPath: config/pic32mz_ef_btadk_ak4954/system/time
  name: sys_time_local.h
  physicalPath: system/time/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 62F39464265EC34979649F761FB4FE57
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mz_ef_btadk_ak4954/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mz_ef_btadk_ak4954/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mz_ef_btadk_ak4954/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FA212DEAE39D4E86EF4E6CB440610FE9
- generatedChecksum: null
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 07A482DAB7473FC475EA656561967B15
  logicalPath: config/pic32mz_ef_btadk_ak4954
  name: p32MZ2048EFM144.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 07A482DAB7473FC475EA656561967B15
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_btadk_ak4954;../src/packs/PIC32MZ2048EFM144_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '40000'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mz_ef_btadk_ak4954;../src/packs/PIC32MZ2048EFM144_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
